Gruntfile.js, docs/index.html, svg-sprite/index.html
Use SVG for Everybody library to support IE browsers up to version 9.
Removes Gridicons SVG inline code and replaces it with the external reference.
IE 9:
=> Add support for older IE browsers

README.md
After a discussion (puPv3-4jW-p2) we noticed we should be more clear about:
1. the ideal sizes of the icon set
2. that `gridicons-my-sites` is a special case of the WordPress logo, and shouldn't be used larger than 36px.
This PR edits the readme with this note:
> **Notes**: the icon set is made to be used exactly at these pixel sizes: 12, 18, 24, 36, 48, 54, 72. However, `gridicon-my-sites` as it's a small-size version of the WordPress logo, shouldn't be used larger than 36px.
/cc @mattmiklic
=> Docs: specified ideal resolutions and exception for my-sites

Gruntfile.js, package.json
Fixes #212
I had copy pasta'd the Calypso config, and missed that https://babeljs.io/docs/plugins/transform-runtime/ requires a hard dependency of `babel-runtime`. I went ahead and removed it since I'm not sure if we need these polyfills
For testing convenience, I published this to `1.1.0-alpha.1`. So you can install this via: `npm install gridicons@next --save`
cc @aduth @sirbrillig
=> Remove babel transform-runtime plugin

package.json, sources/react/index-header.jsx
React 15.5+ [moved PropTypes out of the main `react` package and into a separate `prop-types` package](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes). I'm using `gridicons` for a project and it's now the last dependency that is still throwing off deprecation warnings.
This PR attempts to address. It builds without errors, and addresses the deprecation warnings in my project, but could use thorough testing by someone more familiar with this code and packaging up modules for npm (e.g. should `prop-types` be in `peerDependencies` or `dependencies` see [migration guide](https://github.com/reactjs/prop-types#migrating-from-reactproptypes)). We may have to bump React version to ^0.14.9.
A second commit cleans up some minor linting issues …
=> Adopt React 15.5+ approach to PropTypes

package.json, sources/react/index-header.jsx
Fixes a regression from https://github.com/Automattic/gridicons/pull/226 where if we called
```jsx
<Gridicon icon="add-image" className="foo" />
```
The SVG would only have class `foo` and would be missing `gridicon` and the icon name.
See related: https://github.com/Automattic/wp-calypso/pull/15758
=> Build: Fix classname generation

package.json
This PR will update gridicons to v2.0.2.
@jancavan @folletto any notable changes since v2.0.1? Would it be possible to start keeping track of changes in a changelog. For example:
https://github.com/Automattic/eslint-plugin-wpcalypso/blob/master/CHANGELOG.md
=> Bump to v2.0.2

CHANGELOG.md, package.json
This PR updates Gridicons to `v2.0.3` and `changelog.md`
=> Bump to v2.0.3

README.md
More explicit step-by-step explanation to publish to npm.
Questions:
1. Is it thorough? If I know zero apart from initial Gridicons setup and I follow EXACTLY these steps, do I get the right outcome?
2. We mentioned using the npm support for github branches instead of `1.1.0-alpha.1` tag. I feel it's better, but I probably need a review to make sure I'm not writing bad instructions.
=> Docs: updated NPM details, step by step.

README.md
If you don't read the previous note closely, it'd be easy to think that using Gridicons requires using React. This makes it obvious that it's easy to use Gridicons in non-React projects.
=> Readme: Clarify usage outside a React project

CHANGELOG.md, package.json
This PR updates Gridicons to v2.0.5 and updates changelog.md following this change: Automattic/gridicons#255
=> Bump to v2.0.5

CHANGELOG.md, package.json, sources/react/example-footer.jsx, sources/react/example-header.jsx
Only bumping the version to 2.1.0(-alpha.1, for now) since we're still permitting `^15.3.0`, too.
Relevant for https://github.com/Automattic/wp-calypso/pull/19083
=> React: Allow v16

grunt-tasks/svg-transform-add-g.js
The previous `svg-transform-add-g` grunt task used a blind match on the string, relying on `viewBox="0 0 24 24">` to be at the end of the `<svg>` tag.
This PR updates the script to use a RegEx matching the `<svg>` tag in a more generic way:
* Start: `<svg[^>]*>` (matches anything inside the svg tag that is not a `>`, then gets the `>` as the ending of the tag)
* End: `</svg>` (escaping the `/`)
_This bug was found during testing of #256._ 
1. Delete `/svg-min` folder
2. Run grunt
3. Make sure no SVG that has been re-generated has any change (there should be any changed file in the git tracking)
=> Build: regex-based <g> insertion matching svg tag, to be more reliable

package.json
We were seeing a security warning in this repo:
> The handlebars dependency defined in package.json has a known moderate severity security vulnerability in version range < 4.0.0 and should be updated.
This removes `handlebars` from `package.json` to eliminate that warning.
=> Remove handlebars to get rid of security warning

CHANGELOG.md, package.json
Follow the recent change of adding Zoom in/out icons in this PR: https://github.com/Automattic/gridicons/pull/268, we need to update `package.json` and `changelog.md` to reflect the new version of Gridicons.
=> Bump to v2.1.1

CHANGELOG.md
In #269 we missed adding `create` (#256) that was added to Gridicons after `v2.1` (#260).
=> Docs: added missing "create" note in changelog

CHANGELOG.md
The React update in #260 also bumped the version at the same time without updating the changelog with all the changes happened from the previous version (v2.0.5, #257).
=> Docs: added missing icons in changelog for v2.1.0

CHANGELOG.md
The date in the 2.1.2 changelog note was not correct, fixed to the date of the version bump.
=> Docs: fixed date in 2.1.2 changelog

package.json
This fixes pdfkit to 0.8.3 and prevents the usage of 0.9.0, which causes a regeneration of the pdf icons that we don't want.
See #302 #303 #258 
1. Switch to this branch
2. Try `npm install` then `grunt`
3. Verify with `npm ls pdfkit` that the library version is `0.1.3` and pdfkit is `0.8.3`
4. Make sure no change happens on the generated files
_(Note: the "react" error in `npm ls` is not an issue)._
=> Update package.json: explicitly require pdfkit 0.8.3

CHANGELOG.md, Gruntfile.js, package.json
In Calypso, this will allow us to transition away from the SVG-in-JS icons to a better approach, making use of the spritemap with SVG external content.
The rest of the package is kept as-is, to maintain compatibility.
@blowery I think this is a good approach, but I'd like your input. It should be ok to include these files in the package and depend on them explicitly in Calypso, right?
=> Add spritemap and offsets to package.

CHANGELOG.md, package.json
This patch release pushes a new version that doesn't include a duplicated file.
The file was an artifact of a previous change, with the build process not cleaning it up, so there are no actual changes to the code in this PR.
=> Bump package to 3.3.1.
